### ISSUE TITLE
QQ数据的持久化路径在哪

### ISSUE THREAD

**Issue by yuboabc** [LLOneBot/llonebot.nix#2]
需要将QQ的数据存档路径进行持久化保存, 不然每次重启docker 都会扫码登录.

**Comment by Declarcall** [comment]
--user-data-dir=/root/.config/QQ， 但是我进到容器里发现根本没创建 /root/.config

**Comment by yuboabc** [comment]
直接设置这个就行了?  --user-data-dir 这个有效吗?

**Comment by initialencounter** [comment]
之前是bwrap虚拟的目录， 现在QQ数据将存放到容器的 `/data/.config/QQ` 目录，重启后不需要重新登录了
